name: Build ARM64 Debian Package

on:
  workflow_dispatch: 

jobs:
  build-and-release:
    runs-on: ubuntu-22.04-arm64  # 明确指定 ARM64 运行器

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dependencies
        run: |
          sudo apt-get update && sudo apt-get upgrade;
          sudo apt-get install -y devscripts debhelper dh-make build-essential;

      - name: Build Packages
        run: |
          bash tools/buildutils/build_packages.sh;

      - name: Archive Release
        run: |
          mkdir -p ../release;
          find . -name '*.deb' -exec mv -v {} ../release \;
          find . -name '*.gz' -exec mv -v {} ../release \;
          find . -name '*.tar' -exec mv -v {} ../release \;
          tar -cvf ./android-cuttlefish-aarch64linux.tar.gz ../release;

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "ARM64 Android Cuttlefish Debian Package ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./android-cuttlefish-aarch64linux.tar.gz
          asset_name: cuttlefish-arm64.tar.gz
          asset_content_type: application/vnd.debian.binary-package

